### PR TITLE
Refactor to NoSQLUnit

### PR DESCRIPTION
**Pull request by lordofthejars**
This PR is not meant to be merged but you can see the changes I have made.

You will see that I am not using RestAssured not URL. This is because for me a component test that you want to avoid network (for this reason using Fongo) it should not use the REST API, maybe I will create an integration test for this. 

In this case, I am just testing the DAO, if you would like to test the integration between Resource and DAO, you can still do it, you can deploy both but instead of using RestAssured, just inject the resource class in test and makes a method call directly.

Notice that there is an integration between Arquillian and NoSQLUnit through APE (https://github.com/arquillian/arquillian-extension-persistence/tree/2.0.0/arquillian-ape-nosql/mongodb-ftest) Currently is not working with Fongo, but I will work on it soon.

### CODE REVIEW

**Comment by HasseNasse** [comment]
Wonderful @lordofthejars, I will not merge it but I am very thankful for the help.

I see, I am however curious because there is a Resource testing section in the Component testing chapter of your book "Testing Java Microservices" where we use WireMock etc.

**Comment by lordofthejars** [comment]
Yes, but my point here was since you are not using a real Mongodb (it takes just seconds to be up and running) I supposed that you wanted something super fast, so no network involved so I thought that following this approach of no network, it should be also not networked from resources point. But it was just a feeling it is perfectly fine to do it how you did.

Btw working on APE support for MongoDB and also adding Liberty to have Chameleon support. Thanks for the example since showed me some elements to improve in Arquillian.

And of course thank you very much for buying the book, hope you enjoyed.

**Comment by HasseNasse** [comment]
Happy I could help 👍
Would love to use APE with fongo when that gets released!

Thanks again

**Comment by lordofthejars** [comment]
PR sent, it looks like this: https://github.com/lordofthejars/arquillian-extension-persistence/blob/issue-103/arquillian-ape-nosql/mongodb-ftest/src/test/java/org/arquilian/ape/nosql/mongodb/FongoDbTest.java Of course after review it might change, but you can get an idea.

**Comment by HasseNasse** [comment]
After getting some time off from work I merged this solution and tested it locally, I am not getting the error, however the mongoDatabase is not being populated either.

**Comment by lordofthejars** [comment]
Check my tests you'll see that findAll works, what does not work is the
findById and so on either because Fongo does not support correctly cursors
or for any other case. But check findAll and you'll see that it is
correctly populated.

El ds., 11 d’ag. 2018 a les 13:32, Hassan Nazar (<notifications@github.com>)
va escriure:

**Comment by HasseNasse** [comment]
It's very wierd, I merged your PR and am testing directly on the GreetingDAO test w.o doing any further changes, however the data inside HelloResourceTest.json is not being populated:

```
java.lang.AssertionError: 
Expected size:<3> but was:<1> in:
<[Greeting{greeting='Salam', greetingLanguage='ar'}]>
```

**Comment by lordofthejars** [comment]
Sometimes rebase does not make his job perfectly :) can you try to get from
my repo, clone it locally in your compter and try it there?

El ds., 11 d’ag. 2018 a les 14:06, Hassan Nazar (<notifications@github.com>)
va escriure:

**Comment by HasseNasse** [comment]
Sure ill give it a shot :)

**Comment by HasseNasse** [comment]
Same issue with the failing test on the cloned repo. hmm..

**Comment by HasseNasse** [comment]
Ok, nvm that, it does indeed work.

**Pull request merged**
